# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_item_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='list',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hello.List'),
        ),
    ]
